<?php
declare(strict_types=1);
namespace Undkonsorten\PagetitleTs\ContentObject;

/**
 * This file is part of the TYPO3 CMS extension "pagetitle_ts".
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 * The TYPO3 project - inspiring people to share!
 */

use TYPO3\CMS\Core\Cache\Exception;
use TYPO3\CMS\Core\PageTitle\PageTitleProviderManager;
use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Frontend\ContentObject\ContentObjectGetDataHookInterface;
use TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer;
use TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController;

/**
 * Hook to TypoScript's "getData()" with final page title.
 *
 * This class extends the {@see ContentObjectRenderer::getData()} function by providing functionality
 * to insert the final page title, generated by the PageTitle API. Use it as follows in your TypoScript:
 *
 * <code>
 *   # Insert page title as og:title meta tag
 *   page.meta {
 *     og:title {
 *       data = pagetitle
 *       replace = 1
 *     }
 *   }
 * </code>
 * <output>
 *   <meta property="og:title" content="My page title" />
 * </output>
 *
 * @author Elias Häußler <elias.haeussler@undkonsorten.com>
 * @license GPL-2.0+
 */
class PageTitleGetDataHook implements ContentObjectGetDataHookInterface
{
    /** @var string TypoScript section identifier for getData() hook */
    const GET_DATA_STRING = 'pagetitle';

    /**
     * {@inheritdoc}
     */
    public function getDataExtension($getDataString, array $fields, $sectionValue, $returnValue, ContentObjectRenderer &$parentObject)
    {
        if ($sectionValue === self::GET_DATA_STRING) {
            try {
                $pageTitleProviderManager = GeneralUtility::makeInstance(PageTitleProviderManager::class);
                $returnValue = $pageTitleProviderManager->getTitle();
            } catch (Exception $e) {
                $returnValue = $this->getTypoScriptFrontendController()->page['title'];
            }
        }

        return $returnValue;
    }

    /**
     * @return TypoScriptFrontendController
     */
    protected function getTypoScriptFrontendController(): TypoScriptFrontendController
    {
        return $GLOBALS['TSFE'];
    }
}
